version: '3.7'

services:
  nginx:
    image: nginx:1.13.6-alpine
    volumes:
      - ./nginx/project-a.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    networks:
      - backend
    ports:
      - 7001:80

  php:
    image: php:7.1.11-fpm-alpine3.4
    networks:
      - backend
    volumes:
      - ./public:/var/www/html

networks:
  backend:
    name: backend